version: '3.8'

services:
  # Go Application
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: adwaithadithyan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mock
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./pkg/config/.env:/app/pkg/config/.env
    networks:
      - app-network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: adwaithadithyan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: